import { Ionicons } from "@expo/vector-icons";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ActivityIndicator,
  FlatList,
  KeyboardAvoidingView,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  useWindowDimensions,
  View,
} from "react-native";

import { createCustomer } from "../../api/createCustomer";
import { getAllStates, getCitiesByState } from "../../api/findCitiesApi";
import { getCompanies } from "../../api/getCompanies";
import makeStyles from "./CreateCustomer.styles";

/** Seconds the success dialog stays up before it hands control back. */
const REDIRECT_SECONDS = 3;

/* CompanyDto.isDefault is declared as `private boolean isDefault`, so Lombok's
   getter is isDefault() and Jackson may serialise it as "default". Accept both
   spellings so the right company is still flagged either way. */
const isDefaultCompany = (company) =>
  company?.isDefault === true || company?.default === true;

const companyLabel = (company) =>
  company?.companyName || `Company ${company?.companyId}`;

/** Sentinel option value that clears the default billing company. */
const NO_COMPANY = "";

const EMPTY = {
  customerId: "", // auto-generated by the server; never typed here
  customerName: "",
  alias: "",
  address: "",
  city: "",
  state: "",
  pinCode: "",
  country: "India",
  contactPerson: "",
  telephoneNumber: "",
  mobileNumber: "",
  email: "",
  panNumber: "",
  panName: "",
  gstNumber: "",
  defaultBillingCompanyId: "", // company id held as a string; sent as an Integer
};

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const PAN_RE = /^[A-Z]{5}[0-9]{4}[A-Z]$/;
const GST_RE = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$/;

const SECTIONS = [
  {
    key: "customer",
    label: "",
    fields: [
      {
        name: "customerId",
        label: "Customer ID",
        placeholder: "Auto-generated",
        icon: "id-card-outline",
        keyboardType: "number-pad", // integer id
        optional: true, // assigned by the server, never user-required
        disabled: true, // read-only
      },
      {
        name: "customerName",
        label: "Customer name",
        placeholder: "Balaji Nursery Pvt Ltd",
        icon: "business-outline",
        autoCapitalize: "words",
      },
      {
        name: "alias",
        label: "Alias",
        placeholder: "Short name for lists",
        icon: "pricetag-outline",
        optional: true,
      },
      {
        name: "contactPerson",
        label: "Contact person",
        placeholder: "Who to call",
        icon: "person-outline",
        autoCapitalize: "words",
      },
      {
        name: "mobileNumber",
        label: "Mobile number",
        placeholder: "10-digit mobile",
        icon: "call-outline",
        keyboardType: "phone-pad",
        maxLength: 10,
      },
      {
        name: "telephoneNumber",
        label: "Telephone",
        placeholder: "Landline with STD code",
        icon: "keypad-outline",
        keyboardType: "phone-pad",
        optional: true,
      },
      {
        name: "email",
        label: "Email",
        placeholder: "accounts@company.com",
        icon: "mail-outline",
        keyboardType: "email-address",
        autoCapitalize: "none",
        optional: true,
      },
    ],
  },
  {
    key: "address",
    label: "Address",
    fields: [
      {
        name: "address",
        label: "Street address",
        placeholder: "Plot, street, landmark",
        icon: "location-outline",
        span: 2,
      },
      // State comes first — the city list is fetched for the chosen state.
      {
        name: "state",
        label: "State",
        placeholder: "Select a state",
        icon: "map-outline",
        type: "select",
      },
      {
        name: "city",
        label: "City",
        placeholder: "Select a city",
        icon: "location-outline",
        type: "select",
      },
      {
        name: "pinCode",
        label: "PIN code",
        placeholder: "452001",
        icon: "mail-open-outline",
        keyboardType: "number-pad",
        maxLength: 6,
      },
      {
        name: "country",
        label: "Country",
        placeholder: "India",
        icon: "earth-outline",
        autoCapitalize: "words",
      },
    ],
  },
  {
    key: "tax",
    label: "Tax details",
    fields: [
      {
        name: "panNumber",
        label: "PAN number",
        placeholder: "ABCDE1234F",
        icon: "card-outline",
        autoCapitalize: "characters",
        maxLength: 10,
        optional: true,
      },
      {
        name: "panName",
        label: "Name on PAN",
        placeholder: "As printed on the card",
        icon: "person-circle-outline",
        autoCapitalize: "words",
        optional: true,
      },
      {
        name: "gstNumber",
        label: "GST number",
        placeholder: "23ABCDE1234F1Z5",
        icon: "receipt-outline",
        autoCapitalize: "characters",
        maxLength: 15,
        optional: true,
      },
    ],
  },
  {
    key: "billing",
    label: "Billing",
    fields: [
      {
        name: "defaultBillingCompanyId",
        label: "Default billing company",
        placeholder: "Select a company",
        icon: "business-outline",
        type: "select",
        optional: true,
      },
    ],
  },
];

/** Pack fields into rows adding up to at most `columns` worth of span. */
const packRows = (fields, columns) => {
  const limit = Math.max(1, Number(columns) || 1);
  const rows = [];
  let row = [];
  let used = 0;

  fields.forEach((field) => {
    const span = Math.min(Number(field.span) || 1, limit);
    if (used + span > limit) {
      rows.push(row);
      row = [];
      used = 0;
    }
    row.push({ ...field, span });
    used += span;
  });

  if (row.length) rows.push(row);
  return rows;
};

/** Both endpoints answer with a plain string[] or the ApiResponseModal wrapper. */
const listFrom = (response) => {
  if (Array.isArray(response)) return response;
  if (Array.isArray(response?.payload)) return response.payload;
  return null;
};

const validate = (form) => {
  const errors = {};

  // customerId is auto-generated — not validated here.
  if (!form.customerName.trim()) errors.customerName = "Required.";
  if (!form.address.trim()) errors.address = "Required.";
  if (!form.city.trim()) errors.city = "Required.";
  if (!form.state.trim()) errors.state = "Required.";
  if (!form.country.trim()) errors.country = "Required.";
  if (!form.contactPerson.trim()) errors.contactPerson = "Required.";

  if (!form.pinCode.trim()) errors.pinCode = "Required.";
  else if (!/^\d{6}$/.test(form.pinCode.trim()))
    errors.pinCode = "Enter 6 digits.";

  if (!form.mobileNumber.trim()) errors.mobileNumber = "Required.";
  else if (!/^\d{10}$/.test(form.mobileNumber.trim()))
    errors.mobileNumber = "Enter 10 digits.";

  if (form.email.trim() && !EMAIL_RE.test(form.email.trim()))
    errors.email = "Enter a valid email.";

  if (
    form.panNumber.trim() &&
    !PAN_RE.test(form.panNumber.trim().toUpperCase())
  )
    errors.panNumber = "Looks like ABCDE1234F.";

  if (
    form.gstNumber.trim() &&
    !GST_RE.test(form.gstNumber.trim().toUpperCase())
  )
    errors.gstNumber = "Needs 15 valid characters.";

  return errors;
};

/**
 * Create customer form.
 *
 * Fields scroll; the action bar is pinned below the scroll area so Save
 * and Cancel stay on screen at every size.
 *
 * Customer ID is an integer assigned by the server on save — the field is
 * shown read-only ("Auto-generated") and is not part of the create payload.
 *
 * On save the form confirms in a dialog and counts down before handing
 * control to `onCreated` — the user can leave early or stay and add
 * another customer instead.
 *
 * Props
 *  - onCreated  (customer) => void
 *  - onCancel   () => void
 */
export default function CreateCustomer({ onCreated, onCancel }) {
  const { width, height } = useWindowDimensions();
  const isTablet = width >= 600 && width < 1024;
  const isDesktop = width >= 1024;
  const styles = useMemo(
    () => makeStyles({ width, height, isTablet, isDesktop }),
    [width, height, isTablet, isDesktop],
  );

  const [form, setForm] = useState(EMPTY);
  const [errors, setErrors] = useState({});
  const [focused, setFocused] = useState(null);
  const [saving, setSaving] = useState(false);
  const [banner, setBanner] = useState(null);

  /** Saved customer awaiting redirect — null when the dialog is closed. */
  const [saved, setSaved] = useState(null);
  const [seconds, setSeconds] = useState(REDIRECT_SECONDS);

  /* State / city come from the server; city depends on the chosen state. */
  const [states, setStates] = useState([]);
  const [statesLoading, setStatesLoading] = useState(false);
  const [statesError, setStatesError] = useState(null);

  const [cities, setCities] = useState([]);
  const [citiesLoading, setCitiesLoading] = useState(false);
  const [citiesError, setCitiesError] = useState(null);

  /* Companies back the default-billing-company select. */
  const [companies, setCompanies] = useState([]);
  const [companiesLoading, setCompaniesLoading] = useState(false);
  const [companiesError, setCompaniesError] = useState(null);

  /** Which select is open: "state" | "city" | "defaultBillingCompanyId" | null. */
  const [picker, setPicker] = useState(null);
  const [pickerQuery, setPickerQuery] = useState("");

  /* The org's default company, remembered so resetting the form (Add another,
     Cancel) restores the prefill instead of blanking it. */
  const orgDefaultCompanyRef = useRef("");

  const loadStates = useCallback(async () => {
    setStatesLoading(true);
    setStatesError(null);

    const response = await getAllStates();
    const list = listFrom(response);

    setStatesLoading(false);
    setStates(list ?? []);
    if (!list) setStatesError(response?.message || "Could not load states.");
  }, []);

  useEffect(() => {
    loadStates();
  }, [loadStates]);

  // Guards against a slow reply for a state the user has already changed away
  // from overwriting the current city list.
  const cityReqRef = useRef(0);

  const loadCities = useCallback(async (stateName) => {
    const myReq = ++cityReqRef.current;

    if (!stateName) {
      setCities([]);
      setCitiesLoading(false);
      setCitiesError(null);
      return;
    }

    setCitiesLoading(true);
    setCitiesError(null);

    const response = await getCitiesByState(stateName);
    if (myReq !== cityReqRef.current) return;

    const list = listFrom(response);
    setCitiesLoading(false);
    setCities(list ?? []);
    if (!list) setCitiesError(response?.message || "Could not load cities.");
  }, []);

  useEffect(() => {
    loadCities(form.state);
  }, [form.state, loadCities]);

  /* Companies rarely change and the list is short, so it is loaded once on
     mount. The company flagged isDefault seeds the field, which the user can
     still change or clear. */
  const loadCompanies = useCallback(async () => {
    setCompaniesLoading(true);
    setCompaniesError(null);

    const response = await getCompanies();
    const ok =
      response?.status === "SUCCESS" || response?.status === "NOT_FOUND";
    const list = ok ? response.payload || [] : [];

    setCompaniesLoading(false);
    setCompanies(list);
    if (!ok) {
      setCompaniesError(response?.message || "Could not load companies.");
      return;
    }

    const preset = list.find(isDefaultCompany);
    if (!preset) return;

    orgDefaultCompanyRef.current = String(preset.companyId);
    setForm((prev) =>
      prev.defaultBillingCompanyId
        ? prev
        : { ...prev, defaultBillingCompanyId: orgDefaultCompanyRef.current },
    );
  }, []);

  useEffect(() => {
    loadCompanies();
  }, [loadCompanies]);

  /** Blank form, minus the org default billing company which we keep. */
  const resetForm = useCallback(
    () =>
      setForm({
        ...EMPTY,
        defaultBillingCompanyId: orgDefaultCompanyRef.current,
      }),
    [],
  );

  // Keep the callback fresh without restarting the countdown each render.
  const onCreatedRef = useRef(onCreated);
  useEffect(() => {
    onCreatedRef.current = onCreated;
  }, [onCreated]);

  // One tick per second while the dialog is up; fires onCreated at zero.
  useEffect(() => {
    if (!saved) return undefined;

    if (seconds <= 0) {
      onCreatedRef.current?.(saved);
      return undefined;
    }

    const id = setTimeout(() => setSeconds((s) => s - 1), 1000);
    return () => clearTimeout(id);
  }, [saved, seconds]);

  const setField = (key) => (value) => {
    setForm((prev) => ({ ...prev, [key]: value }));
    setErrors((prev) => (prev[key] ? { ...prev, [key]: undefined } : prev));
  };

  const openPicker = (name) => {
    setPickerQuery("");
    setPicker(name);
  };

  const closePicker = () => {
    setPicker(null);
    setPickerQuery("");
  };

  /** Picking a different state invalidates whatever city was chosen. */
  const pickOption = (name, value) => {
    setForm((prev) =>
      name === "state" && prev.state !== value
        ? { ...prev, state: value, city: "" }
        : { ...prev, [name]: value },
    );
    setErrors((prev) => ({
      ...prev,
      [name]: undefined,
      ...(name === "state" ? { city: undefined } : null),
    }));
    closePicker();
  };

  /* Every picker list is normalised to { value, label } so one dialog can serve
     the plain string lists (state, city) and the CompanyDto objects alike —
     companies store an id but display a name. */
  const stateOptions = useMemo(
    () => states.map((name) => ({ value: String(name), label: String(name) })),
    [states],
  );
  const cityOptions = useMemo(
    () => cities.map((name) => ({ value: String(name), label: String(name) })),
    [cities],
  );
  const companyOptions = useMemo(
    () => [
      { value: NO_COMPANY, label: "No default billing company" },
      ...companies.map((company) => ({
        value: String(company.companyId),
        label: companyLabel(company),
        badge: isDefaultCompany(company) ? "DEFAULT" : null,
      })),
    ],
    [companies],
  );

  const pickerConfig =
    picker === "state"
      ? {
          title: "Select state",
          search: "Search states",
          options: stateOptions,
          loading: statesLoading,
          error: statesError,
          retry: loadStates,
          empty: "No states available.",
        }
      : picker === "city"
        ? {
            title: "Select city",
            search: "Search cities",
            options: cityOptions,
            loading: citiesLoading,
            error: citiesError,
            retry: () => loadCities(form.state),
            empty: `No cities listed for ${form.state || "this state"}.`,
          }
        : picker === "defaultBillingCompanyId"
          ? {
              title: "Default billing company",
              search: "Search companies",
              options: companyOptions,
              loading: companiesLoading,
              error: companiesError,
              retry: loadCompanies,
              empty: "No companies configured.",
            }
          : null;

  const pickerOptions = useMemo(() => {
    const all = pickerConfig?.options ?? [];
    const term = pickerQuery.trim().toLowerCase();
    if (!term) return all;
    return all.filter((option) => option.label.toLowerCase().includes(term));
  }, [pickerConfig?.options, pickerQuery]);

  /** Text shown on a closed select — companies hold an id but show a name. */
  const selectDisplay = (name) => {
    if (name !== "defaultBillingCompanyId") return form[name];
    const match = companies.find(
      (company) => String(company.companyId) === form[name],
    );
    return match ? companyLabel(match) : "";
  };

  /** Leave now instead of waiting out the countdown. */
  const goNow = () => {
    const customer = saved;
    setSaved(null);
    onCreatedRef.current?.(customer);
  };

  /** Stay put with a blank form. */
  const addAnother = () => {
    setSaved(null);
    setSeconds(REDIRECT_SECONDS);
    setBanner(null);
  };

  const handleSubmit = async () => {
    const found = validate(form);
    setErrors(found);

    if (Object.keys(found).length) {
      setBanner({ type: "error", text: "Check the highlighted fields." });
      return;
    }

    setSaving(true);
    setBanner(null);

    const payload = Object.fromEntries(
      Object.entries(form).map(([key, value]) => [key, value.trim()]),
    );
    payload.panNumber = payload.panNumber.toUpperCase();
    payload.gstNumber = payload.gstNumber.toUpperCase();

    // CustomerDto.defaultBillingCompanyId is an Integer; blank means none.
    payload.defaultBillingCompanyId = payload.defaultBillingCompanyId
      ? Number(payload.defaultBillingCompanyId)
      : null;

    // Server auto-generates the integer customerId — don't send it.
    delete payload.customerId;

    const response = await createCustomer(payload);
    setSaving(false);

    if (response?.status === "SUCCESS") {
      resetForm();
      setErrors({});
      setSeconds(REDIRECT_SECONDS);
      setSaved(response.payload ?? payload);
    } else {
      const message = response?.message || "Could not save this customer.";
      setBanner({ type: "error", text: message });
    }
  };

  const renderField = (field) => {
    const {
      name,
      label,
      placeholder,
      icon,
      optional = false,
      keyboardType = "default",
      autoCapitalize = "sentences",
      maxLength,
      span = 1,
      disabled = false,
      type = "text",
    } = field;

    // flexBasis 0 keeps span widths exact regardless of placeholder length.
    const flexStyle = styles.isPhone
      ? null
      : { flexGrow: Number(span) || 1, flexShrink: 1, flexBasis: 0 };

    const labelNode = (
      <Text style={styles.label} numberOfLines={1}>
        {label}
        {optional ? null : <Text style={styles.required}> *</Text>}
      </Text>
    );

    const errorNode = errors[name] ? (
      <Text style={styles.errorText} numberOfLines={1}>
        {errors[name]}
      </Text>
    ) : null;

    if (type === "select") {
      const value = selectDisplay(name);
      // City can't be chosen before a state narrows the list.
      const locked = disabled || (name === "city" && !form.state);
      const loading =
        name === "state"
          ? statesLoading
          : name === "city"
            ? citiesLoading
            : companiesLoading;

      return (
        <View key={name} style={[styles.field, flexStyle]}>
          {labelNode}

          <Pressable
            onPress={() => openPicker(name)}
            disabled={locked}
            style={({ hovered, pressed }) => [
              styles.inputWrap,
              picker === name && styles.inputWrapFocused,
              errors[name] && styles.inputWrapError,
              (hovered || pressed) && styles.inputWrapHover,
              locked && styles.inputWrapDisabled,
              locked && { opacity: 0.6 },
            ]}
          >
            <Ionicons
              name={icon}
              size={styles.iconSize}
              color={errors[name] ? styles.danger : styles.placeholderColor}
            />
            <Text
              numberOfLines={1}
              style={[styles.selectValue, !value && styles.selectPlaceholder]}
            >
              {value || (locked ? "Pick a state first" : placeholder)}
            </Text>
            {loading ? (
              <ActivityIndicator size="small" color={styles.placeholderColor} />
            ) : (
              <Ionicons
                name="chevron-down"
                size={styles.iconSize}
                color={styles.placeholderColor}
              />
            )}
          </Pressable>

          {errorNode}
        </View>
      );
    }

    return (
      <View key={name} style={[styles.field, flexStyle]}>
        {labelNode}

        <View
          style={[
            styles.inputWrap,
            focused === name && styles.inputWrapFocused,
            errors[name] && styles.inputWrapError,
            disabled && styles.inputWrapDisabled,
            disabled && { opacity: 0.6 },
          ]}
        >
          <Ionicons
            name={icon}
            size={styles.iconSize}
            color={errors[name] ? styles.danger : styles.placeholderColor}
          />
          <TextInput
            style={styles.input}
            value={form[name]}
            onChangeText={setField(name)}
            onFocus={() => setFocused(name)}
            onBlur={() => setFocused(null)}
            placeholder={placeholder}
            placeholderTextColor={styles.placeholderColor}
            keyboardType={keyboardType}
            autoCapitalize={autoCapitalize}
            autoCorrect={false}
            maxLength={maxLength}
            editable={!disabled}
          />
        </View>

        {errorNode}
      </View>
    );
  };

  return (
    <View style={styles.screen}>
      <KeyboardAvoidingView
        style={styles.keyboardWrap}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
      >
        <ScrollView
          style={styles.scroll}
          contentContainerStyle={styles.scrollContent}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          {banner ? (
            <View
              style={[
                styles.banner,
                banner.type === "error"
                  ? styles.bannerError
                  : styles.bannerSuccess,
              ]}
            >
              <Ionicons
                name={
                  banner.type === "error"
                    ? "alert-circle-outline"
                    : "checkmark-circle-outline"
                }
                size={styles.iconSize}
                color={banner.type === "error" ? styles.danger : styles.green}
              />
              <Text style={styles.bannerText}>{banner.text}</Text>
            </View>
          ) : null}

          {SECTIONS.map((section) => (
            <View style={styles.section} key={section.key}>
              {section.label ? (
                <Text style={styles.sectionLabel}>{section.label}</Text>
              ) : null}

              {packRows(section.fields, styles.columns).map((row, index) => {
                const filled = row.reduce(
                  (sum, f) => sum + (Number(f.span) || 1),
                  0,
                );
                const remainder = (Number(styles.columns) || 1) - filled;

                return (
                  <View style={styles.row} key={`${section.key}-${index}`}>
                    {row.map(renderField)}
                    {!styles.isPhone && remainder > 0 ? (
                      <View
                        style={[
                          styles.spacer,
                          { flexGrow: remainder, flexShrink: 1, flexBasis: 0 },
                        ]}
                      />
                    ) : null}
                  </View>
                );
              })}
            </View>
          ))}
        </ScrollView>

        {/* Outside the ScrollView — always reachable. */}
        <View style={styles.actions}>
          <Pressable
            style={({ pressed }) => [
              styles.button,
              styles.buttonGhost,
              pressed && styles.buttonPressed,
            ]}
            onPress={() => {
              resetForm();
              setErrors({});
              setBanner(null);
              onCancel?.();
            }}
            disabled={saving}
          >
            <Text style={[styles.buttonText, styles.buttonGhostText]}>
              CANCEL
            </Text>
          </Pressable>

          <Pressable
            style={({ pressed }) => [
              styles.button,
              styles.buttonPrimary,
              pressed && styles.buttonPressed,
              saving && styles.buttonDisabled,
            ]}
            onPress={handleSubmit}
            disabled={saving}
          >
            {saving ? (
              <ActivityIndicator size="small" color="#FFFFFF" />
            ) : (
              <Ionicons
                name="checkmark"
                size={styles.iconSize}
                color="#FFFFFF"
              />
            )}
            <Text style={styles.buttonText}>
              {saving ? "SAVING…" : "SAVE CUSTOMER"}
            </Text>
          </Pressable>
        </View>
      </KeyboardAvoidingView>

      {/* State / city picker — a dialog so long lists never fight the layout. */}
      <Modal
        visible={!!pickerConfig}
        transparent
        animationType="fade"
        onRequestClose={closePicker}
      >
        <Pressable style={styles.modalBackdrop} onPress={closePicker}>
          <Pressable style={styles.pickerCard} onPress={() => {}}>
            <View style={styles.pickerHeader}>
              <Text style={styles.pickerTitle}>{pickerConfig?.title}</Text>
              <Pressable
                onPress={closePicker}
                hitSlop={10}
                style={({ pressed }) => pressed && styles.buttonPressed}
              >
                <Ionicons
                  name="close"
                  size={22}
                  color={styles.placeholderColor}
                />
              </Pressable>
            </View>

            <View style={styles.pickerSearch}>
              <Ionicons
                name="search-outline"
                size={styles.iconSize}
                color={styles.placeholderColor}
              />
              <TextInput
                style={styles.input}
                value={pickerQuery}
                onChangeText={setPickerQuery}
                placeholder={pickerConfig?.search}
                placeholderTextColor={styles.placeholderColor}
                autoCorrect={false}
                autoCapitalize="words"
              />
            </View>

            {pickerConfig?.loading ? (
              <View style={styles.pickerState}>
                <ActivityIndicator size="small" color={styles.navy} />
                <Text style={styles.pickerStateText}>Loading…</Text>
              </View>
            ) : pickerConfig?.error ? (
              <Pressable
                style={styles.pickerState}
                onPress={() => pickerConfig.retry?.()}
              >
                <Ionicons
                  name="alert-circle-outline"
                  size={22}
                  color={styles.danger}
                />
                <Text style={styles.pickerStateText}>{pickerConfig.error}</Text>
                <Text style={styles.pickerRetry}>TAP TO RETRY</Text>
              </Pressable>
            ) : pickerOptions.length === 0 ? (
              <View style={styles.pickerState}>
                <Ionicons
                  name="search-outline"
                  size={22}
                  color={styles.placeholderColor}
                />
                <Text style={styles.pickerStateText}>
                  {pickerQuery.trim()
                    ? `Nothing matches “${pickerQuery.trim()}”.`
                    : pickerConfig?.empty}
                </Text>
              </View>
            ) : (
              <FlatList
                style={styles.pickerList}
                data={pickerOptions}
                keyExtractor={(item, index) => `${item.value}-${index}`}
                keyboardShouldPersistTaps="handled"
                renderItem={({ item }) => {
                  const active = form[picker] === item.value;
                  return (
                    <Pressable
                      onPress={() => pickOption(picker, item.value)}
                      style={({ hovered, pressed }) => [
                        styles.pickerOption,
                        (hovered || pressed) && styles.pickerOptionHover,
                      ]}
                    >
                      <Ionicons
                        name={active ? "checkmark-circle" : "ellipse-outline"}
                        size={18}
                        color={active ? styles.navy : styles.placeholderColor}
                      />
                      <Text
                        numberOfLines={1}
                        style={[
                          styles.pickerOptionText,
                          active && styles.pickerOptionTextActive,
                        ]}
                      >
                        {item.label}
                      </Text>
                      {item.badge ? (
                        <Text style={styles.pickerBadge}>{item.badge}</Text>
                      ) : null}
                    </Pressable>
                  );
                }}
              />
            )}
          </Pressable>
        </Pressable>
      </Modal>

      {/* Success dialog — confirms first, redirects after the countdown. */}
      <Modal
        visible={!!saved}
        transparent
        animationType="fade"
        onRequestClose={goNow}
      >
        <View style={styles.modalBackdrop}>
          <View style={styles.modalCard}>
            <View style={styles.modalIcon}>
              <Ionicons name="checkmark" size={34} color="#FFFFFF" />
            </View>

            <Text style={styles.modalTitle}>Customer saved</Text>

            <Text style={styles.modalBody}>
              {saved?.customerName || "The customer"}
              {saved?.customerId ? ` (${saved.customerId})` : ""} is ready to
              use on quotations and invoices.
            </Text>

            <Text style={styles.modalCountdown}>
              Returning in {Math.max(seconds, 0)}…
            </Text>

            <View style={styles.modalActions}>
              <Pressable
                style={({ pressed }) => [
                  styles.button,
                  styles.buttonGhost,
                  styles.modalButton,
                  pressed && styles.buttonPressed,
                ]}
                onPress={addAnother}
              >
                <Text style={[styles.buttonText, styles.buttonGhostText]}>
                  ADD ANOTHER
                </Text>
              </Pressable>

              <Pressable
                style={({ pressed }) => [
                  styles.button,
                  styles.buttonPrimary,
                  styles.modalButton,
                  pressed && styles.buttonPressed,
                ]}
                onPress={goNow}
              >
                <Text style={styles.buttonText}>GO NOW</Text>
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}
